export const BCU_COURSES = [
    "Accounting and Finance",
    "Architecture",
    "Artificial Intelligence",
    "Biomedical Science",
    "Business Management",
    "Civil Engineering",
    "Computer Science",
    "Creative Writing",
    "Criminology",
    "Cyber Security",
    "Data Science",
    "Digital Marketing",
    "Education",
    "Electrical and Electronic Engineering",
    "Fashion Design",
    "Film Production",
    "Forensic Science",
    "Games Technology",
    "Graphic Design",
    "Health and Social Care",
    "Interior Design",
    "International Business",
    "Journalism",
    "Law",
    "Marketing",
    "Mechanical Engineering",
    "Media and Communication",
    "Music Technology",
    "Nursing",
    "Physiotherapy",
    "Product Design",
    "Psychology",
    "Social Work",
    "Software Engineering",
    "Sport and Exercise Science",
    "Web Development and Design",
];
